[package]
name = "dr_base_framework"
authors = ["Kevin Fischer <kfischer_okarin@yahoo.co.jp>"]
version = "0.1.0"
homepage = "https://github.com/kfischer-okarin/dr_base_framework"
keywords = []

# Optional:
# documentation = "https://example.com"
# repository = "http://github.com/example/example"

# Which files do you want to be automatically required from your package.
requires = ["lib/dr_base_framework.rb"]


[package.installs]

[dragonruby]
version = "3"
edition = "standard"
